"""empty message

Revision ID: 26dc29939b01
Revises: 869010ff13ec
Create Date: 2022-07-15 00:50:06.500105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26dc29939b01'
down_revision = '869010ff13ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda', sa.Column('tanggal_real', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agenda', 'tanggal_real')
    # ### end Alembic commands ###
