"""empty message

Revision ID: 4dde55fb8c9a
Revises: 73ee9c7ceb5c
Create Date: 2022-07-08 10:57:34.811818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dde55fb8c9a'
down_revision = '73ee9c7ceb5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.String(length=30), nullable=False),
    sa.Column('waktu', sa.String(length=10), nullable=False),
    sa.Column('tempat', sa.String(length=80), nullable=False),
    sa.Column('agenda', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('absen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('instansi', sa.String(length=80), nullable=False),
    sa.Column('jabatan', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hp', sa.String(length=20), nullable=False),
    sa.Column('agenda_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agenda_id'], ['agenda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('absen')
    op.drop_table('agenda')
    # ### end Alembic commands ###
