"""empty message

Revision ID: 9600f8966e2d
Revises: 
Create Date: 2022-07-10 20:48:40.443185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9600f8966e2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.String(length=30), nullable=False),
    sa.Column('waktu', sa.String(length=10), nullable=False),
    sa.Column('tempat', sa.String(length=80), nullable=False),
    sa.Column('agenda', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('absen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('instansi', sa.String(length=80), nullable=False),
    sa.Column('jabatan', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hp', sa.String(length=20), nullable=False),
    sa.Column('ttd', sa.String(length=50), nullable=False),
    sa.Column('qrcode', sa.String(length=50), nullable=False),
    sa.Column('checkin', sa.String(length=30), nullable=True),
    sa.Column('agenda_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agenda_id'], ['agenda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('absen')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('agenda')
    # ### end Alembic commands ###
