"""empty message

Revision ID: f7cb0f92dff1
Revises: 9600f8966e2d
Create Date: 2022-07-10 21:14:34.137349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7cb0f92dff1'
down_revision = '9600f8966e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda', sa.Column('link', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agenda', 'link')
    # ### end Alembic commands ###
